@baseUrl = http://localhost:8080/api/tasks

### Create
# @name createTask
POST {{baseUrl}}
Content-Type: application/json

{ "name": "Test", "description": "     ", "priority": "LOW" }

### get all  task 
GET {{baseUrl}}

### update task
PATCH {{baseUrl}}/10110
Content-Type: application/json

{
    "name": "rowel",
    "description": "",
    "status": "IN_PROGRESS",
    "priority": "HIGH",
    "dueDate": "2026-10-12T00:04:32.059465800Z"
}