spring.application.name=task-api

spring.datasource.url=jdbc:sqlserver://localhost:1434;instanceName=SQLExpress01;databaseName=taskapi_db;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=best_in_Me0909
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.table=flyway_schema_history